### ISSUE TITLE
Merhaba ufak bir sorun.

### ISSUE THREAD

**Issue by noneym** [aozisik/turkce#2]
Merhaba eline sağlık class işime yaradı fakat mongo dbye kayıt eklerken direk senin class la eklemeye kalktığımda mongo gb değeri object olarak görüyordu. sorunu strval() functionu kullanarak çözdüm, sende class da strval kullanarak değeri string'e çevirirsen iyi olur gibi.

**Comment by aozisik** [comment]
Merhaba 👋 

Paketi kullandığınız için teşekkürler.
2.1.0 versiyonuyla eklenen `yap()` metodunu kullanarak sonucu string olarak alabilirsiniz.

Sürüm notları: https://github.com/aozisik/turkce/releases/tag/v2.1.0
Readme: https://github.com/aozisik/turkce#sonucu-string-olarak-dönme
